CREATE TABLE CLIENTES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PRIMEIRO_NOME VARCHAR(20) NOT NULL,
    ULTIMO_NOME VARCHAR(20) NOT NULL,
    CNH VARCHAR(11) NOT NULL,
    ID_PEDIDO INTEGER
);

CREATE TABLE CARROS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(20) NOT NULL,
    PLACA VARCHAR(7) NOT NULL,
    VALOR_DIARIA FLOAT NOT NULL,
    ID_PEDIDO INTEGER
);

PEDIDO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_CARRO INTEGER NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    DATA_LOCACAO DATE NOT NULL,
    DIAS_LOCACAO INT NOT NULL,
    VALOR_TOTAL FLOAT NOT NULL
);